name: Fortran CI

on: [push, pull_request]

jobs:
  cpu-gfortran:
    name: Build & Run (gfortran CPU)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fortran (gfortran)
        uses: fortran-lang/setup-fortran@v1.6.3
        with:
          compiler: gcc          # or gfortran
          version: 13            # version you want
      - name: Build
        run: ${{ env.FC }} main.f90 -o main   # env.FC is provided by setup-fortran
      - name: Run
        run: ./main

  openacc-nvfortran:
    name: Build & Run (nvfortran + OpenACC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fortran (nvfortran)
        uses: fortran-lang/setup-fortran@v1.6.3
        with:
          compiler: nvidia-hpc    # this picks nvfortran
          version: 25.1           # or another version that supports your OpenACC needs
      - name: Build with nvfortran
        run: ${{ env.FC }} -acc -Minfo=accel main.f90 -o main
      - name: Run
        run: ./main
