name: Fortran CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compiler: gcc
            version: 13
          - compiler: nvidia-hpc
            version: 25.1

    steps:
      - uses: actions/checkout@v4

      # Install compiler first
      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1.6.3
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      # Cache NVIDIA HPC SDK only for nvfortran
      - name: Cache NVIDIA HPC SDK
        if: matrix.compiler == 'nvidia-hpc'
        uses: actions/cache@v4
        with:
          # This is the actual path setup-fortran installs the SDK to
          path: |
            ~/.fortran-lang/cache/nvidia-hpc/linux-x86_64-${{ matrix.version }}
          key: nvhpc-${{ runner.os }}-v${{ matrix.version }}
          restore-keys: |
            nvhpc-${{ runner.os }}-

      # Build
      - name: Build
        run: |
          if [ "${{ matrix.compiler }}" == "nvidia-hpc" ]; then
            ${{ env.FC }} -acc -Minfo=accel main.f90 -o main
          else
            ${{ env.FC }} main.f90 -o main
          fi

      # Run
      - name: Run
        run: ./main
