name: Fortran CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gfortran, nvidia-hpc]
        version: [13, 25.1]  # gfortran 13 and nvfortran 25.1

    steps:
      - uses: actions/checkout@v4

      # Cache NVIDIA HPC SDK only for nvfortran
      - name: Cache NVIDIA HPC SDK
        if: matrix.compiler == 'nvidia-hpc'
        uses: actions/cache@v4
        with:
          path: ~/.fortran-lang/cache/nvidia-hpc
          key: nvhpc-${{ runner.os }}-v${{ matrix.version }}
          restore-keys: |
            nvhpc-${{ runner.os }}-

      # Install compiler
      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1.6.3
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      # Build
      - name: Build
        run: |
          if [ "${{ matrix.compiler }}" == "nvidia-hpc" ]; then
            ${{ env.FC }} -acc -Minfo=accel main.f90 -o main
          else
            ${{ env.FC }} main.f90 -o main
          fi

      # Run
      - name: Run
        run: ./main
